package li.cil.oc.common.asm

import li.cil.oc.common.asm.template.SimpleComponentImpl
import li.cil.oc.integration.Mods
import net.minecraft.launchwrapper.IClassTransformer
import net.minecraft.launchwrapper.LaunchClassLoader
import net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper
import org.apache.logging.log4j.LogManager
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes
import org.objectweb.asm.tree.*

object ObfNames {
    @JvmField val Class_EntityHanging = arrayOf("net/minecraft/entity/EntityHanging")
    @JvmField val Class_EntityLiving = arrayOf("net/minecraft/entity/EntityLiving")
    @JvmField val Class_RenderLiving = arrayOf("net/minecraft/client/renderer/entity/RenderLiving")
    @JvmField val Class_TileEntity = arrayOf("net/minecraft/tileentity/TileEntity")
    @JvmField val Field_leashNBTTag = arrayOf("leashNBTTag", "field_110170_bx")
    @JvmField val Field_leashedToEntity = arrayOf("leashedToEntity", "leashHolder", "field_110168_bw")
    @JvmField val Method_recreateLeash = arrayOf("recreateLeash", "func_110165_bF")
    @JvmField val Method_recreateLeashDesc = arrayOf("()V")
    @JvmField val Method_renderLeash = arrayOf("renderLeash", "func_110827_b")
    @JvmField val Method_renderLeashDesc = arrayOf("(Lnet/minecraft/entity/EntityLiving;DDDFF)V")
    @JvmField val Method_validate = arrayOf("validate", "func_145829_t")
    @JvmField val Method_invalidate = arrayOf("invalidate", "func_145843_s")
    @JvmField val Method_onChunkUnload = arrayOf("onChunkUnload", "func_76623_d")
    @JvmField val Method_readFromNBT = arrayOf("readFromNBT", "func_145839_a")
    @JvmField val Method_writeToNBT = arrayOf("writeToNBT", "func_189515_b")
}

object ClassTransformer {
    @JvmField var hadErrors = false
    @JvmField var hadSimpleComponentErrors = false
}

class ClassTransformerImpl : IClassTransformer {
    private val loader = javaClass.classLoader as LaunchClassLoader
    private val log = LogManager.getLogger("OpenComputers")

    override fun transform(obfName: String, name: String, basicClass: ByteArray): ByteArray {
        if (basicClass == null || name.startsWith("scala.")) return basicClass
        var transformedClass = basicClass
        try {
            if (!name.startsWith("net.minecraft.")
                && !name.startsWith("net.minecraftforge.")
                && !name.startsWith("li.cil.oc.common.asm.")
                && !name.startsWith("li.cil.oc.integration.")) {
                if (name.startsWith("li.cil.oc.")) {
                    // Strip foreign interfaces from scala generated classes. This is
                    // primarily intended to clean up mix-ins / synthetic classes
                    // generated by Scala.
                    val classNode = newClassNode(transformedClass)
                    val missingInterfaces = classNode.interfaces.filter { !classExists(it as String) }
                    for (interfaceName in missingInterfaces) {
                        log.trace("Stripping interface $interfaceName from class $name because it is missing.")
                    }
                    classNode.interfaces.removeAll(missingInterfaces.toSet())

                    val missingClasses = classNode.innerClasses.filter { clazz ->
                        (clazz as InnerClassNode).outerName != null && !classExists(clazz.outerName)
                    }
                    for (innerClass in missingClasses) {
                        log.trace("Stripping inner class ${(innerClass as InnerClassNode).name} from class $name because its type ${innerClass.outerName} is missing.")
                    }
                    classNode.innerClasses.removeAll(missingClasses.toSet())

                    val incompleteMethods = classNode.methods.filter { method ->
                        missingFromSignature((method as MethodNode).desc).isNotEmpty()
                    }
                    for (method in incompleteMethods) {
                        val missing = missingFromSignature((method as MethodNode).desc).joinToString(", ")
                        log.trace("Stripping method ${method.name} from class $name because the following types in its signature are missing: $missing")
                    }
                    classNode.methods.removeAll(incompleteMethods.toSet())

                    // Inject available interfaces where requested.
                    if (classNode.visibleAnnotations != null) {
                        fun injectInterface(annotation: AnnotationNode) {
                            val values = annotation.values?.chunked(2)?.associate { it[0] to it[1] } ?: emptyMap()
                            val interfaceName = values["value"] as? String
                            val modid = values["modid"] as? String
                            if (interfaceName != null && modid != null) {
                                val mod = Mods.All.find { it.id == modid }
                                if (mod != null) {
                                    if (mod.isModAvailable) {
                                        val interfaceDesc = interfaceName.replace(".", "/")
                                        val node = classNodeFor(interfaceDesc)
                                        if (node == null) {
                                            log.warn("Interface $interfaceName not found, skipping injection.")
                                        } else {
                                            val missing = node.methods
                                                .filterNot { im -> classNode.methods.any { cm -> (im as MethodNode).name == (cm as MethodNode).name && im.desc == cm.desc } }
                                                .map { method -> "Missing implementation of ${(method as MethodNode).name + method.desc}" }
                                            if (missing.isEmpty()) {
                                                log.info("Injecting interface $interfaceName into $name.")
                                                classNode.interfaces.add(interfaceDesc)
                                            } else {
                                                log.warn("Missing implementations for interface $interfaceName, skipping injection.")
                                                missing.forEach { log.warn(it) }
                                                ClassTransformer.hadErrors = true
                                            }
                                        }
                                    } else {
                                        log.info("Skipping interface $interfaceName from missing mod $modid.")
                                    }
                                } else {
                                    log.warn("Skipping interface $interfaceName from unknown mod $modid.")
                                    ClassTransformer.hadErrors = true
                                }
                            }
                        }

                        classNode.visibleAnnotations.find { (it as AnnotationNode).desc == "Lli/cil/oc/common/asm/Injectable\$Interface;" }?.let {
                            injectInterface(it as AnnotationNode)
                        }

                        classNode.visibleAnnotations.find { (it as AnnotationNode).desc == "Lli/cil/oc/common/asm/Injectable\$InterfaceList;" }?.let { annotation ->
                            val values = (annotation as AnnotationNode).values?.chunked(2)?.associate { it[0] to it[1] } ?: emptyMap()
                            @Suppress("UNCHECKED_CAST")
                            (values["value"] as? Iterable<AnnotationNode>)?.forEach { injectInterface(it) }
                        }
                    }

                    transformedClass = writeClass(classNode)
                }

                run {
                    val classNode = newClassNode(transformedClass)
                    if (classNode.interfaces.contains("li/cil/oc/api/network/SimpleComponent") &&
                        (classNode.visibleAnnotations == null || !classNode.visibleAnnotations.any { annotation ->
                            annotation != null && (annotation as AnnotationNode).desc == "Lli/cil/oc/api/network/SimpleComponent\$SkipInjection;"
                        })) {
                        try {
                            transformedClass = injectEnvironmentImplementation(classNode)
                            log.info("Successfully injected component logic into class $name.")
                        } catch (e: Throwable) {
                            log.warn("Failed injecting component logic into class $name.", e)
                            ClassTransformer.hadSimpleComponentErrors = true
                        }
                    }
                }
            }

            // Inject some code into the EntityLiving classes recreateLeash method to allow
            // proper loading of leashes tied to entities using the leash upgrade. This is
            // necessary because entities only save the entity they are leashed to if that
            // entity is an EntityLivingBase - which drones, for example, are not, for good
            // reason. We work around this by re-leashing them in the load method of the
            // leash upgrade. The leashed entity would then still unleash itself and, more
            // problematically drop a leash item. To avoid this, we extend the
            //    if (this.isLeashed && this.field_110170_bx != null)
            // check to read
            //    if (this.isLeashed && this.field_110170_bx != null && this.leashedToEntity == null)
            // which should not interfere with any existing logic, but avoid leashing
            // restored manually in the load phase to not be broken again.
            if (ObfNames.Class_EntityLiving.contains(name.replace('.', '/'))) {
                val classNode = newClassNode(transformedClass)
                insertInto(classNode, ObfNames.Method_recreateLeash, ObfNames.Method_recreateLeashDesc) { instructions ->
                    val insArray = instructions.toArray()
                    for (i in 0 until insArray.size - 2) {
                        val varNode = insArray[i] as? VarInsnNode ?: continue
                        val fieldNode = insArray[i + 1] as? FieldInsnNode ?: continue
                        val jumpNode = insArray[i + 2] as? JumpInsnNode ?: continue

                        if (varNode.opcode == Opcodes.ALOAD && varNode.`var` == 0 &&
                            fieldNode.opcode == Opcodes.GETFIELD && ObfNames.Field_leashNBTTag.contains(fieldNode.name) &&
                            jumpNode.opcode == Opcodes.IFNULL) {

                            val field = classNode.fields.find { f -> ObfNames.Field_leashedToEntity.contains((f as FieldNode).name) } as? FieldNode
                            if (field != null) {
                                val toInject = InsnList()
                                toInject.add(VarInsnNode(Opcodes.ALOAD, 0))
                                toInject.add(FieldInsnNode(Opcodes.GETFIELD, classNode.name, field.name, field.desc))
                                toInject.add(JumpInsnNode(Opcodes.IFNONNULL, jumpNode.label))
                                instructions.insert(jumpNode, toInject)
                                return@insertInto true
                            }
                        }
                    }
                    false
                }?.let { transformedClass = it }
            }

            // Little change to the renderer used to render leashes to center it on drones.
            // This injects the code
            //   if (entity instanceof Drone) {
            //     d5 = 0.0;
            //     d6 = 0.0;
            //     d7 = -0.25;
            //   }
            // before the `instanceof EntityHanging` check in func_110827_b.
            if (ObfNames.Class_RenderLiving.contains(name.replace('.', '/'))) {
                val classNode = newClassNode(transformedClass)
                insertInto(classNode, ObfNames.Method_renderLeash, ObfNames.Method_renderLeashDesc) { instructions ->
                    val insArray = instructions.toArray()
                    for (i in 0 until insArray.size - 2) {
                        val varNode = insArray[i] as? VarInsnNode ?: continue
                        val typeNode = insArray[i + 1] as? TypeInsnNode ?: continue
                        val jumpNode = insArray[i + 2] as? JumpInsnNode ?: continue

                        if (varNode.opcode == Opcodes.ALOAD && varNode.`var` == 10 &&
                            typeNode.opcode == Opcodes.INSTANCEOF && ObfNames.Class_EntityHanging.contains(typeNode.desc) &&
                            jumpNode.opcode == Opcodes.IFEQ) {

                            val toInject = InsnList()
                            toInject.add(VarInsnNode(Opcodes.ALOAD, 10))
                            toInject.add(TypeInsnNode(Opcodes.INSTANCEOF, "li/cil/oc/common/entity/Drone"))
                            val skip = LabelNode()
                            toInject.add(JumpInsnNode(Opcodes.IFEQ, skip))
                            toInject.add(LdcInsnNode(0.0))
                            toInject.add(VarInsnNode(Opcodes.DSTORE, 17))
                            toInject.add(LdcInsnNode(0.0))
                            toInject.add(VarInsnNode(Opcodes.DSTORE, 19))
                            toInject.add(LdcInsnNode(-0.25))
                            toInject.add(VarInsnNode(Opcodes.DSTORE, 21))
                            toInject.add(skip)
                            instructions.insertBefore(varNode, toInject)
                            return@insertInto true
                        }
                    }
                    false
                }?.let { transformedClass = it }
            }

            return transformedClass
        } catch (t: Throwable) {
            log.warn("Something went wrong!", t)
            ClassTransformer.hadErrors = true
            return basicClass
        }
    }

    private fun insertInto(classNode: ClassNode, methodNames: Array<String>, methodDescs: Array<String>, inserter: (InsnList) -> Boolean): ByteArray? {
        val methodNode = classNode.methods.find { method ->
            methodNames.contains((method as MethodNode).name) && methodDescs.contains(method.desc)
        } as? MethodNode
        return if (methodNode != null) {
            if (inserter(methodNode.instructions)) {
                log.info("Successfully patched ${classNode.name}.${methodNames[0]}.")
                writeClass(classNode, ClassWriter.COMPUTE_MAXS or ClassWriter.COMPUTE_FRAMES)
            } else {
                log.warn("Failed patching ${classNode.name}.${methodNames[0]}, injection point not found.")
                ClassTransformer.hadErrors = true
                null
            }
        } else {
            log.warn("Failed patching ${classNode.name}.${methodNames[0]}, method not found.")
            ClassTransformer.hadErrors = true
            null
        }
    }

    private fun classExists(name: String): Boolean {
        return loader.getClassBytes(name) != null ||
            loader.getClassBytes(FMLDeobfuscatingRemapper.INSTANCE.unmap(name)) != null ||
            try {
                loader.findClass(name.replace('/', '.')) != null
            } catch (e: ClassNotFoundException) {
                false
            }
    }

    private fun missingFromSignature(desc: String): List<String> {
        return Regex("""L([^;]+);""").findAll(desc).map { it.groupValues[1] }.filter { !classExists(it) }.toList()
    }

    fun injectEnvironmentImplementation(classNode: ClassNode): ByteArray {
        log.trace("Injecting methods from Environment interface into ${classNode.name}.")
        if (!isTileEntity(classNode)) {
            throw InjectionFailedException("Found SimpleComponent on something that isn't a tile entity, ignoring.")
        }

        val template = classNodeFor("li/cil/oc/common/asm/template/SimpleEnvironment")
            ?: throw InjectionFailedException("Could not find SimpleComponent template!")

        fun inject(methodName: String, signature: String, required: Boolean = false) {
            fun filter(method: MethodNode) = method.name == methodName && method.desc == signature
            if (classNode.methods.any { filter(it as MethodNode) }) {
                if (required) {
                    throw InjectionFailedException("Could not inject method '$methodName$signature' because it was already present!")
                }
            } else {
                template.methods.find { filter(it as MethodNode) }?.let { method ->
                    classNode.methods.add(method)
                } ?: throw AssertionError()
            }
        }
        inject("node", "()Lli/cil/oc/api/network/Node;", required = true)
        inject("onConnect", "(Lli/cil/oc/api/network/Node;)V")
        inject("onDisconnect", "(Lli/cil/oc/api/network/Node;)V")
        inject("onMessage", "(Lli/cil/oc/api/network/Message;)V")

        log.trace("Injecting / wrapping overrides for required tile entity methods.")
        fun replace(methodName: String, methodNameSrg: String, desc: String) {
            val mapper = FMLDeobfuscatingRemapper.INSTANCE
            fun filter(method: MethodNode): Boolean {
                val descDeObf = mapper.mapMethodDesc(method.desc)
                val methodNameDeObf = mapper.mapMethodName(mapper.unmap(ObfNames.Class_TileEntity[0]), method.name, method.desc)
                val areSamePlain = method.name + descDeObf == methodName + desc
                val areSameDeObf = methodNameDeObf + descDeObf == methodNameSrg + desc
                return areSamePlain || areSameDeObf
            }
            if (classNode.methods.any { method ->
                    (method as MethodNode).name == methodName + SimpleComponentImpl.PostFix && mapper.mapMethodDesc(method.desc) == desc
                }) {
                throw InjectionFailedException("Delegator method name '${methodName + SimpleComponentImpl.PostFix}' is already in use.")
            }
            val existingMethod = classNode.methods.find { filter(it as MethodNode) } as? MethodNode
            if (existingMethod != null) {
                log.trace("Found original implementation of '$methodName', wrapping.")
                existingMethod.name = methodName + SimpleComponentImpl.PostFix
            } else {
                log.trace("No original implementation of '$methodName', will inject override.")
                tailrec fun ensureNonFinalIn(name: String?) {
                    if (name != null) {
                        val node = classNodeFor(name)
                        if (node != null) {
                            val method = node.methods.find { filter(it as MethodNode) } as? MethodNode
                            if (method != null) {
                                if ((method.access and Opcodes.ACC_FINAL) != 0) {
                                    throw InjectionFailedException("Method '$methodName' is final in superclass ${node.name.replace('/', '.')}.")
                                }
                            }
                            ensureNonFinalIn(node.superName)
                        }
                    }
                }
                ensureNonFinalIn(classNode.superName)
                template.methods.find { (it as MethodNode).name == methodName + SimpleComponentImpl.PostFix }?.let { method ->
                    classNode.methods.add(method)
                } ?: throw AssertionError("Couldn't find '${methodName + SimpleComponentImpl.PostFix}' in template implementation.")
            }
            template.methods.find { filter(it as MethodNode) }?.let { method ->
                classNode.methods.add(method)
            } ?: throw AssertionError("Couldn't find '$methodName' in template implementation.")
        }
        replace(ObfNames.Method_validate[0], ObfNames.Method_validate[1], "()V")
        replace(ObfNames.Method_invalidate[0], ObfNames.Method_invalidate[1], "()V")
        replace(ObfNames.Method_onChunkUnload[0], ObfNames.Method_onChunkUnload[1], "()V")
        replace(ObfNames.Method_readFromNBT[0], ObfNames.Method_readFromNBT[1], "(Lnet/minecraft/nbt/NBTTagCompound;)V")
        replace(ObfNames.Method_writeToNBT[0], ObfNames.Method_writeToNBT[1], "(Lnet/minecraft/nbt/NBTTagCompound;)Lnet/minecraft/nbt/NBTTagCompound;")

        log.trace("Injecting interface.")
        classNode.interfaces.add("li/cil/oc/common/asm/template/SimpleComponentImpl")

        return writeClass(classNode, ClassWriter.COMPUTE_MAXS or ClassWriter.COMPUTE_FRAMES)
    }

    tailrec fun isTileEntity(classNode: ClassNode?): Boolean {
        if (classNode == null) return false
        log.trace("Checking if class ${classNode.name} is a TileEntity...")
        return ObfNames.Class_TileEntity.contains(FMLDeobfuscatingRemapper.INSTANCE.map(classNode.name)) ||
            (classNode.superName != null && isTileEntity(classNodeFor(classNode.superName)))
    }

    tailrec fun isAssignable(parent: ClassNode?, child: ClassNode?): Boolean {
        return parent != null && child != null && !isFinal(parent) && (
            parent.name == "java/lang/Object" ||
                parent.name == child.name ||
                parent.name == child.superName ||
                child.interfaces.contains(parent.name) ||
                (child.superName != null && isAssignable(parent, classNodeFor(child.superName)))
            )
    }

    fun isFinal(node: ClassNode): Boolean = (node.access and Opcodes.ACC_FINAL) != 0

    fun isInterface(node: ClassNode?): Boolean = node != null && (node.access and Opcodes.ACC_INTERFACE) != 0

    fun classNodeFor(name: String): ClassNode? {
        val namePlain = name.replace('/', '.')
        var bytes = loader.getClassBytes(namePlain)
        if (bytes != null) return newClassNode(bytes)
        val nameObfed = FMLDeobfuscatingRemapper.INSTANCE.unmap(name).replace('/', '.')
        bytes = loader.getClassBytes(nameObfed)
        return if (bytes == null) null else newClassNode(bytes)
    }

    fun newClassNode(data: ByteArray): ClassNode {
        val classNode = ClassNode()
        ClassReader(data).accept(classNode, 0)
        return classNode
    }

    fun writeClass(classNode: ClassNode, flags: Int = ClassWriter.COMPUTE_MAXS): ByteArray {
        val writer = object : ClassWriter(flags) {
            // Implementation without class loads, avoids https://github.com/MinecraftForge/FML/issues/655
            override fun getCommonSuperClass(type1: String, type2: String): String {
                val node1 = classNodeFor(type1)
                val node2 = classNodeFor(type2)
                return when {
                    isAssignable(node1, node2) -> node1!!.name
                    isAssignable(node2, node1) -> node2!!.name
                    isInterface(node1) || isInterface(node2) -> "java/lang/Object"
                    else -> {
                        var parent = node1?.superName?.let { classNodeFor(it) }
                        while (parent != null && parent.superName != null && !isAssignable(parent, node2)) {
                            parent = classNodeFor(parent.superName)
                        }
                        parent?.name ?: "java/lang/Object"
                    }
                }
            }
        }
        classNode.accept(writer)
        return writer.toByteArray()
    }

    class InjectionFailedException(message: String) : Exception(message)
}
