@file:Suppress("ConstPropertyName")

package li.cil.oc

import li.cil.oc.util.ItemUtils

object Constants {

    object BlockName {
        const val Adapter = "adapter"
        const val Assembler = "assembler"
        const val Cable = "cable"
        const val Capacitor = "capacitor"
        const val CarpetedCapacitor = "carpetedcapacitor"
        const val CaseCreative = "casecreative"
        const val CaseTier1 = "case1"
        const val CaseTier2 = "case2"
        const val CaseTier3 = "case3"
        const val ChameliumBlock = "chameliumblock"
        const val Charger = "charger"
        const val Disassembler = "disassembler"
        const val DiskDrive = "diskdrive"
        const val Endstone = "endstone"
        const val Geolyzer = "geolyzer"
        const val HologramTier1 = "hologram1"
        const val HologramTier2 = "hologram2"
        const val Keyboard = "keyboard"
        const val Microcontroller = "microcontroller"
        const val MotionSensor = "motionsensor"
        const val NetSplitter = "netsplitter"
        const val PowerConverter = "powerconverter"
        const val PowerDistributor = "powerdistributor"
        const val Print = "print"
        const val Printer = "printer"
        const val Raid = "raid"
        const val Redstone = "redstone"
        const val Relay = "relay"
        const val Robot = "robot"
        const val RobotAfterimage = "robotafterimage"
        const val ScreenTier1 = "screen1"
        const val ScreenTier2 = "screen2"
        const val ScreenTier3 = "screen3"
        const val Rack = "rack"
        const val Transposer = "transposer"
        const val Waypoint = "waypoint"

        @JvmStatic
        @Suppress("FunctionName")
        fun Case(tier: Int): String = ItemUtils.caseNameWithTierSuffix("case", tier)
    }

    object ItemName {
        const val AbstractBusCard = "abstractbuscard"
        const val Acid = "acid"
        const val Alu = "alu"
        const val Analyzer = "analyzer"
        const val AngelUpgrade = "angelupgrade"
        const val APUCreative = "apucreative"
        const val APUTier1 = "apu1"
        const val APUTier2 = "apu2"
        const val ArrowKeys = "arrowkeys"
        const val BatteryUpgradeTier1 = "batteryupgrade1"
        const val BatteryUpgradeTier2 = "batteryupgrade2"
        const val BatteryUpgradeTier3 = "batteryupgrade3"
        const val ButtonGroup = "buttongroup"
        const val Card = "card"
        const val CardContainerTier1 = "cardcontainer1"
        const val CardContainerTier2 = "cardcontainer2"
        const val CardContainerTier3 = "cardcontainer3"
        const val Chamelium = "chamelium"
        const val ChipTier1 = "chip1"
        const val ChipTier2 = "chip2"
        const val ChipTier3 = "chip3"
        const val ChunkloaderUpgrade = "chunkloaderupgrade"
        const val CircuitBoard = "circuitboard"
        const val ComponentBusTier1 = "componentbus1"
        const val ComponentBusTier2 = "componentbus2"
        const val ComponentBusTier3 = "componentbus3"
        const val ComponentBusCreative = "componentbuscreative"
        const val CPUTier1 = "cpu1"
        const val CPUTier2 = "cpu2"
        const val CPUTier3 = "cpu3"
        const val CraftingUpgrade = "craftingupgrade"
        const val ControlUnit = "cu"
        const val CuttingWire = "cuttingwire"
        const val DatabaseUpgradeTier1 = "databaseupgrade1"
        const val DatabaseUpgradeTier2 = "databaseupgrade2"
        const val DatabaseUpgradeTier3 = "databaseupgrade3"
        const val DataCardTier1 = "datacard1"
        const val DataCardTier2 = "datacard2"
        const val DataCardTier3 = "datacard3"
        const val DebugCard = "debugcard"
        const val Debugger = "debugger"
        const val DiamondChip = "chipdiamond"
        const val Disk = "disk"
        const val DiskDriveMountable = "diskdrivemountable"
        const val Drone = "drone"
        const val DroneCaseCreative = "dronecasecreative"
        const val DroneCaseTier1 = "dronecase1"
        const val DroneCaseTier2 = "dronecase2"
        const val EEPROM = "eeprom"
        const val ExperienceUpgrade = "experienceupgrade"
        const val Floppy = "floppy"
        const val GeneratorUpgrade = "generatorupgrade"
        const val GraphicsCardTier1 = "graphicscard1"
        const val GraphicsCardTier2 = "graphicscard2"
        const val GraphicsCardTier3 = "graphicscard3"
        const val HDDTier1 = "hdd1"
        const val HDDTier2 = "hdd2"
        const val HDDTier3 = "hdd3"
        const val HoverBoots = "hoverboots"
        const val HoverUpgradeTier1 = "hoverupgrade1"
        const val HoverUpgradeTier2 = "hoverupgrade2"
        const val InkCartridgeEmpty = "inkcartridgeempty"
        const val InkCartridge = "inkcartridge"
        const val InternetCard = "internetcard"
        const val Interweb = "interweb"
        const val InventoryControllerUpgrade = "inventorycontrollerupgrade"
        const val InventoryUpgrade = "inventoryupgrade"
        const val LeashUpgrade = "leashupgrade"
        const val LinkedCard = "linkedcard"
        const val LuaBios = "luabios"
        const val MFU = "mfu"
        const val Manual = "manual"
        const val MicrocontrollerCaseCreative = "microcontrollercasecreative"
        const val MicrocontrollerCaseTier1 = "microcontrollercase1"
        const val MicrocontrollerCaseTier2 = "microcontrollercase2"
        const val Nanomachines = "nanomachines"
        const val NavigationUpgrade = "navigationupgrade"
        const val NetworkCard = "lancard"
        const val NumPad = "numpad"
        const val OpenOS = "openos"
        const val PistonUpgrade = "pistonupgrade"
        const val StickyPistonUpgrade = "stickypistonupgrade"
        const val Present = "present"
        const val PrintedCircuitBoard = "printedcircuitboard"
        const val RAMTier1 = "ram1"
        const val RAMTier2 = "ram2"
        const val RAMTier3 = "ram3"
        const val RAMTier4 = "ram4"
        const val RAMTier5 = "ram5"
        const val RAMTier6 = "ram6"
        const val RawCircuitBoard = "rawcircuitboard"
        const val RedstoneCardTier1 = "redstonecard1"
        const val RedstoneCardTier2 = "redstonecard2"
        const val ServerCreative = "servercreative"
        const val ServerTier1 = "server1"
        const val ServerTier2 = "server2"
        const val ServerTier3 = "server3"
        const val SignUpgrade = "signupgrade"
        const val SolarGeneratorUpgrade = "solargeneratorupgrade"
        const val Tablet = "tablet"
        const val TabletCaseCreative = "tabletcasecreative"
        const val TabletCaseTier1 = "tabletcase1"
        const val TabletCaseTier2 = "tabletcase2"
        const val TankControllerUpgrade = "tankcontrollerupgrade"
        const val TankUpgrade = "tankupgrade"
        const val Terminal = "terminal"
        const val TerminalServer = "terminalserver"
        const val TexturePicker = "texturepicker"
        const val TractorBeamUpgrade = "tractorbeamupgrade"
        const val TradingUpgrade = "tradingupgrade"
        const val Transistor = "transistor"
        const val UpgradeContainerTier1 = "upgradecontainer1"
        const val UpgradeContainerTier2 = "upgradecontainer2"
        const val UpgradeContainerTier3 = "upgradecontainer3"
        const val WirelessNetworkCardTier1 = "wlancard1"
        const val WirelessNetworkCardTier2 = "wlancard2"
        const val WorldSensorCard = "worldsensorcard"
        const val Wrench = "wrench"

        @JvmStatic
        fun DroneCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("dronecase", tier)

        @JvmStatic
        fun MicrocontrollerCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("microcontrollercase", tier)

        @JvmStatic
        fun TabletCase(tier: Int): String = ItemUtils.caseNameWithTierSuffix("tabletcase", tier)
    }

    object DeviceInfo {
        const val DefaultVendor = "MightyPirates GmbH & Co. KG"
        const val Scummtech = "Scummtech, Inc."
    }
}
